site_name: Llama

theme:
    name: material
    features:
        - content.code.copy
        - navigation.instant
        - navigation.tracking

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

# Page tree
nav:
    - Getting Started: index.md
    - Authentication: auth.md
    - Walkthrough Example: example.md
    - Python Library: python_library.md
    - Batching: batching.md
    - Error Handling: error_handling.md
    - Advanced: advanced.md
    - LLM:
          - __init__: LLM/__init__.md
          - __call__: LLM/__call__.md
          - add_data: LLM/add_data.md
          - improve: LLM/improve.md
          - submit_job: LLM/submit_job.md
          - check_job_status: LLM/check_job_status.md
          - get_job_results: LLM/get_job_results.md
          - cancel_job: LLM/cancel_job.md
          - sample: LLM/sample.md
